version: "3"

services:
  saaya:
    container_name: saaya
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: python3 main.py
    
  go-cqhttp:
    container_name: go-cqhttp
    image: ghcr.io/mrs4s/go-cqhttp:master
    ports: 
      - 5700:5700
    volumes:
      - ./cqhttp:/data
